site_name: Pizzoo
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API reference: api.md
theme:
  name: mkdocs
  color_mode: dark
  navigation_depth: 3
  nav_style: primary
  user_color_mode_toggle: true
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          show_root_heading: true
          show_root_full_path: false
          show_symbol_type_heading: true
          members_order: alphabetical
          docstring_style: google
          merge_init_into_class: true
          show_signature: true # default is true, adds parameters to name
          separate_signature: true
    default_handler: python
