site_name: Pizzoo
nav:
  - Introduction: index.md
  - Installation: installation.md
  - Getting started:
    - Drawing and animating: drawing.md
    - Rendering a template: template.md
    - Building your first game: game.md
  - Integrate your device: integration.md
  - API reference: api.md
repo_url: https://github.com/pabletos/pizzoo
theme:
  name: material
  color_mode: dark
  navigation_depth: 3
  nav_style: primary
  user_color_mode_toggle: true
  logo: assets/images/pizzoo-light.png
  favicon: assets/images/favicon.ico
  features:
    - search.suggest
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.footer
    - header.autohide
  palette:
    scheme: slate
    primary: pink
  font:
    text: Lato
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pablo-huet-carrasco/
    - icon: fontawesome/brands/github
      link: https://github.com/pabletos
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [..]
        options:
          show_root_heading: true
          show_root_full_path: false
          show_symbol_type_heading: true
          members_order: alphabetical
          docstring_style: google
          merge_init_into_class: true
          show_signature: true # default is true, adds parameters to name
          separate_signature: true
    default_handler: python
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

